spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codexray?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
