package com.codexray.llm;

import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.List;

@Service
@Profile("dev")
public class StubLlmClient implements LlmClient {

    @Override
    public String analyze(String repoPath) {
        List<String> files = new ArrayList<>();
        try {
            Files.walkFileTree(Path.of(repoPath), new SimpleFileVisitor<>() {
                @Override
                public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
                    files.add(file.getFileName().toString());
                    return FileVisitResult.CONTINUE;
                }
            });
        } catch (IOException e) {
            // ignore
        }

        long javaCount = files.stream().filter(f -> f.endsWith(".java")).count();
        long pyCount = files.stream().filter(f -> f.endsWith(".py")).count();
        long jsCount = files.stream().filter(f -> f.endsWith(".js") || f.endsWith(".ts")).count();

        String primaryLang = "Unknown";
        if (javaCount > pyCount && javaCount > jsCount) primaryLang = "Java";
        else if (pyCount > javaCount && pyCount > jsCount) primaryLang = "Python";
        else if (jsCount > 0) primaryLang = "JavaScript/TypeScript";

        return """
                {
                  "summary": "This is a stub analysis report generated by the dev LLM client.",
                  "primaryLanguage": "%s",
                  "fileCount": %d,
                  "score": 72,
                  "techStack": ["%s"],
                  "verdict": "Looks decent, but this is a stub — real analysis coming soon."
                }
                """.formatted(primaryLang, files.size(), primaryLang);
    }

    @Override
    public String chat(String repoPath, String question) {
        return "[Dev Stub] 这是一个模拟回答。你的问题是：" + question
                + "\n\n当前仓库路径：" + repoPath
                + "\n\n切换到 prod profile 使用真实的 LLM 问答功能。";
    }
}
